export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
}
export enum TokenType {
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}

export enum CircleOccasion {
  BIRTHDAY = 'BIRTHDAY',
  WEDDING = 'WEDDING',
  NEW_BABY = 'NEW_BABY',
  GRADUATION = 'GRADUATION',
  BEREAVEMENT = 'BEREAVEMENT',
  RECOVERY = 'RECOVERY',
  HOUSEWARMING = 'HOUSEWARMING',
  COMMUNITY_SUPPORT = 'COMMUNITY_SUPPORT',
  EMERGENCY_ASSISTANCE = 'EMERGENCY_ASSISTANCE',
  OTHER = 'OTHER',
}
export enum CirclePrivacy {
  PRIVATE = 'PRIVATE',
  LINK_ONLY = 'LINK_ONLY',
  COMMUNITY = 'COMMUNITY',
}
export enum CircleStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  FUNDED = 'FUNDED',
  FULFILLING = 'FULFILLING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
export enum GiftItemStatus {
  ACTIVE = 'ACTIVE',
  FUNDED = 'FUNDED',
  PURCHASED = 'PURCHASED',
  UNAVAILABLE = 'UNAVAILABLE',
}
export enum ContributionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REFUNDED = 'REFUNDED',
}
export enum PaymentProvider {
  PAYSTACK = 'PAYSTACK',
  MANUAL = 'MANUAL',
}
export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}
export enum CircleActivityType {
  CIRCLE_CREATED = 'CIRCLE_CREATED',
  CIRCLE_PUBLISHED = 'CIRCLE_PUBLISHED',
  GOAL_UPDATED = 'GOAL_UPDATED',
  CONTRIBUTION_RECEIVED = 'CONTRIBUTION_RECEIVED',
  ITEM_FUNDED = 'ITEM_FUNDED',
  UPDATE_POSTED = 'UPDATE_POSTED',
  FULFILLMENT_UPDATED = 'FULFILLMENT_UPDATED',
  GIFT_DELIVERED = 'GIFT_DELIVERED',
  RECEIPT_CONFIRMED = 'RECEIPT_CONFIRMED',
  CIRCLE_CANCELLED = 'CIRCLE_CANCELLED',
}
export enum FulfillmentStatus {
  PENDING = 'PENDING',
  PURCHASING = 'PURCHASING',
  PACKING = 'PACKING',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CONFIRMED = 'CONFIRMED',
}
export enum NotificationType {
  INVITATION = 'INVITATION',
  CONTRIBUTION_RECEIVED = 'CONTRIBUTION_RECEIVED',
  CIRCLE_UPDATE = 'CIRCLE_UPDATE',
  GOAL_REACHED = 'GOAL_REACHED',
  FULFILLMENT_UPDATE = 'FULFILLMENT_UPDATE',
  DELIVERY = 'DELIVERY',
  SYSTEM = 'SYSTEM',
}

export enum ModerationTargetType {
  USER = 'USER',
  CIRCLE = 'CIRCLE',
  CIRCLE_UPDATE = 'CIRCLE_UPDATE',
  CONTRIBUTION = 'CONTRIBUTION',
}

export enum ModerationReason {
  FRAUD = 'FRAUD',
  MISLEADING = 'MISLEADING',
  HARASSMENT = 'HARASSMENT',
  PRIVACY = 'PRIVACY',
  PROHIBITED_CONTENT = 'PROHIBITED_CONTENT',
  OTHER = 'OTHER',
}

export enum ModerationStatus {
  OPEN = 'OPEN',
  REVIEWING = 'REVIEWING',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}
