import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1789827472404 implements MigrationInterface {
    name = 'Init1789827472404'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."circle_activities_type_enum" AS ENUM('CIRCLE_CREATED', 'CIRCLE_PUBLISHED', 'GOAL_UPDATED', 'CONTRIBUTION_RECEIVED', 'ITEM_FUNDED', 'UPDATE_POSTED', 'FULFILLMENT_UPDATED', 'GIFT_DELIVERED', 'RECEIPT_CONFIRMED', 'CIRCLE_CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "circle_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "type" "public"."circle_activities_type_enum" NOT NULL, "description" character varying(255) NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_51cc56d3e09176cc49a77fec411" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_activities_circle_created" ON "circle_activities" ("circle_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "circle_updates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "author_id" uuid NOT NULL, "title" character varying(140) NOT NULL, "message" text NOT NULL, "image_url" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7880d8fcaad7662b21f2f11980d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(120) NOT NULL, "description" text, "icon_url" text, "sort_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."gift_items_status_enum" AS ENUM('ACTIVE', 'FUNDED', 'PURCHASED', 'UNAVAILABLE')`);
        await queryRunner.query(`CREATE TABLE "gift_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "category_id" uuid, "name" character varying(120) NOT NULL, "emoji" character varying(32), "category_label" character varying(120), "client_reference" character varying(120), "description" text, "quantity" integer NOT NULL DEFAULT '1', "target_amount" numeric(14,2) NOT NULL, "funded_amount" numeric(14,2) NOT NULL DEFAULT '0', "product_url" text, "status" "public"."gift_items_status_enum" NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_83c492f2ef473ca4ac337ed2897" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_gift_items_circle_status" ON "gift_items" ("circle_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."contributions_provider_enum" AS ENUM('PAYSTACK', 'MANUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."contributions_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "contributions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "contributor_id" uuid, "gift_item_id" uuid, "guest_name" character varying(100), "guest_email" character varying(255), "guest_phone" character varying(30), "amount" numeric(14,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "provider" "public"."contributions_provider_enum" NOT NULL DEFAULT 'PAYSTACK', "payment_reference" character varying NOT NULL, "idempotency_key" character varying(160), "payment_method" character varying(32) NOT NULL DEFAULT 'card', "status" "public"."contributions_status_enum" NOT NULL DEFAULT 'PENDING', "message" text, "show_name" boolean NOT NULL DEFAULT true, "show_amount" boolean NOT NULL DEFAULT true, "show_message" boolean NOT NULL DEFAULT true, "provider_payload" jsonb, "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b3e8c3b51b14b3180fbdd7e03bb" UNIQUE ("payment_reference"), CONSTRAINT "PK_ca2b4f39eb9e32a61278c711f79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_contributions_idempotency_key" ON "contributions" ("idempotency_key") WHERE "idempotency_key" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_contributions_user_status" ON "contributions" ("contributor_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_contributions_circle_status" ON "contributions" ("circle_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."fulfillments_status_enum" AS ENUM('PENDING', 'PURCHASING', 'PACKING', 'READY_FOR_DELIVERY', 'IN_TRANSIT', 'DELIVERED', 'CONFIRMED')`);
        await queryRunner.query(`CREATE TABLE "fulfillments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "status" "public"."fulfillments_status_enum" NOT NULL DEFAULT 'PENDING', "delivery_address" jsonb, "address_status" character varying(24) NOT NULL DEFAULT 'pending', "purchase_order_status" character varying(32) NOT NULL DEFAULT 'not_requested', "courier_name" character varying(120), "tracking_number" character varying(120), "tracking_url" text, "proof_url" text, "note" text, "dispatched_at" TIMESTAMP WITH TIME ZONE, "delivered_at" TIMESTAMP WITH TIME ZONE, "confirmed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f20ee44c54cf1880b632ea57056" UNIQUE ("circle_id"), CONSTRAINT "REL_f20ee44c54cf1880b632ea5705" UNIQUE ("circle_id"), CONSTRAINT "PK_cb1805f0398d3d001737de76df3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "email" character varying(255), "phone" character varying(30), "code" character varying(64) NOT NULL, "token_hash" text, "batch_id" uuid, "channel" character varying(16), "message" text, "status" "public"."invitations_status_enum" NOT NULL DEFAULT 'PENDING', "accepted_by_id" uuid, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "accepted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_dfcfae6af22931048ef73078418" UNIQUE ("code"), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_invitations_token_hash" ON "invitations" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_invitations_circle_status" ON "invitations" ("circle_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."circles_occasion_enum" AS ENUM('BIRTHDAY', 'WEDDING', 'NEW_BABY', 'GRADUATION', 'BEREAVEMENT', 'RECOVERY', 'HOUSEWARMING', 'COMMUNITY_SUPPORT', 'EMERGENCY_ASSISTANCE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."circles_privacy_enum" AS ENUM('PRIVATE', 'LINK_ONLY', 'COMMUNITY')`);
        await queryRunner.query(`CREATE TYPE "public"."circles_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'FUNDED', 'FULFILLING', 'COMPLETED', 'CANCELLED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "circles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizer_id" uuid NOT NULL, "slug" character varying(160) NOT NULL, "title" character varying(140) NOT NULL, "occasion" "public"."circles_occasion_enum" NOT NULL, "story" text, "recipient_name" character varying(100) NOT NULL, "recipient_relationship" character varying(24), "recipient_city" character varying(80), "recipient_country_code" character varying(2), "recipient_email" character varying(255), "recipient_phone" character varying(30), "cover_image_url" text, "cover_asset_id" character varying(120), "cover_alt" character varying(255), "privacy" "public"."circles_privacy_enum" NOT NULL DEFAULT 'LINK_ONLY', "status" "public"."circles_status_enum" NOT NULL DEFAULT 'DRAFT', "target_amount" numeric(14,2) NOT NULL, "amount_raised" numeric(14,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'NGN', "funding_mode" character varying(20), "flex_buffer_percent" integer NOT NULL DEFAULT '0', "deadline" TIMESTAMP WITH TIME ZONE NOT NULL, "delivery_address" jsonb, "delivery_collection_mode" character varying(40), "allow_general_contributions" boolean NOT NULL DEFAULT true, "supporter_count" integer NOT NULL DEFAULT '0', "publish_idempotency_key" character varying(160), "version" integer NOT NULL DEFAULT '1', "is_hidden" boolean NOT NULL DEFAULT false, "published_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "recipient_token_hash" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_420be18c025f652dd7ec506aca3" UNIQUE ("slug"), CONSTRAINT "PK_8348b53fdd4f7b6c0b3a6a2f61f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_circles_publish_idempotency_key" ON "circles" ("publish_idempotency_key") WHERE "publish_idempotency_key" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_circles_discovery" ON "circles" ("privacy", "status", "deadline") `);
        await queryRunner.query(`CREATE INDEX "IDX_circles_organizer_status" ON "circles" ("organizer_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('INVITATION', 'CONTRIBUTION_RECEIVED', 'CIRCLE_UPDATE', 'GOAL_REACHED', 'FULFILLMENT_UPDATE', 'DELIVERY', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(140) NOT NULL, "message" text NOT NULL, "data" jsonb, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_read" ON "notifications" ("user_id", "read_at") `);
        await queryRunner.query(`CREATE TYPE "public"."tokens_type_enum" AS ENUM('REFRESH_TOKEN')`);
        await queryRunner.query(`CREATE TABLE "tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" character varying NOT NULL, "type" "public"."tokens_type_enum" NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6a8ca5961656d13c16c04079dd3" UNIQUE ("token"), CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_tokens_user_type" ON "tokens" ("user_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255), "google_id" character varying(255), "avatar_url" text, "phone" character varying(30), "country" character varying NOT NULL DEFAULT 'Nigeria', "currency" character varying(3) NOT NULL DEFAULT 'NGN', "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER', "is_suspended" boolean NOT NULL DEFAULT false, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_0bd5012aeb82628e07f6a1be53b" UNIQUE ("google_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_reports_target_type_enum" AS ENUM('USER', 'CIRCLE', 'CIRCLE_UPDATE', 'CONTRIBUTION')`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_reports_reason_enum" AS ENUM('FRAUD', 'MISLEADING', 'HARASSMENT', 'PRIVACY', 'PROHIBITED_CONTENT', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_reports_status_enum" AS ENUM('OPEN', 'REVIEWING', 'RESOLVED', 'DISMISSED')`);
        await queryRunner.query(`CREATE TABLE "moderation_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reporter_id" uuid NOT NULL, "target_type" "public"."moderation_reports_target_type_enum" NOT NULL, "target_id" uuid NOT NULL, "reason" "public"."moderation_reports_reason_enum" NOT NULL, "details" text, "status" "public"."moderation_reports_status_enum" NOT NULL DEFAULT 'OPEN', "reviewed_by_id" uuid, "resolution_note" text, "resolved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a40784ec3803830fe974b4b85fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_moderation_target" ON "moderation_reports" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_moderation_status_created" ON "moderation_reports" ("status", "created_at") `);
        await queryRunner.query(`CREATE TABLE "contribution_ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contribution_id" uuid NOT NULL, "circle_id" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, "currency" character varying(3) NOT NULL, "direction" character varying(16) NOT NULL DEFAULT 'credit', "status" character varying(24) NOT NULL DEFAULT 'posted', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c5b2974bf7233f7059834ae4f6" UNIQUE ("contribution_id"), CONSTRAINT "PK_0138439e3f213e08cbccae0a53e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "circle_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "contribution_id" uuid, "kind" character varying(24) NOT NULL DEFAULT 'organizer_message', "message" text NOT NULL, "reply_email" character varying(255), "status" character varying(24) NOT NULL DEFAULT 'queued', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c7930d2e1987152a79e605f24d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_circle_messages_circle_created" ON "circle_messages" ("circle_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "circle_broadcasts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "message" text NOT NULL, "channels" jsonb NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'queued', "recipient_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a059618db59afae56eff0413e00" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "type" character varying(24) NOT NULL, "wishlist_item_ids" uuid array NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'under_review', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "circle_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "user_id" uuid NOT NULL, "invitation_id" uuid, "role" character varying(24) NOT NULL DEFAULT 'contributor', "status" character varying(24) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9f367ab2be82a42317f440e56bc" UNIQUE ("invitation_id"), CONSTRAINT "UQ_circle_membership_user" UNIQUE ("circle_id", "user_id"), CONSTRAINT "PK_439621c0f758782fff164e880d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_address_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "circle_id" uuid NOT NULL, "encrypted_payload" text NOT NULL, "status" character varying(24) NOT NULL DEFAULT 'saved', "confirmed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9107d6197c090a7c85054c3ec37" UNIQUE ("circle_id"), CONSTRAINT "PK_4edf723a4e556b644c8692a4ddc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "catalog_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "description" text, "merchant_name" character varying(160) NOT NULL, "merchant_verified" boolean NOT NULL DEFAULT true, "price_amount" numeric(14,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "city" character varying(80), "available" boolean NOT NULL DEFAULT true, "delivery_estimate" character varying(120), "image_url" text, "product_url" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_dd1c29828c10a599d894b9b6535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_catalog_items_search" ON "catalog_items" ("name", "city", "currency") `);
        await queryRunner.query(`ALTER TABLE "circle_activities" ADD CONSTRAINT "FK_e3eede368064d5f8a770329d68f" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_updates" ADD CONSTRAINT "FK_feb81287d37d9124092520f6a10" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_updates" ADD CONSTRAINT "FK_80efa3fc9b52b316940185090dc" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gift_items" ADD CONSTRAINT "FK_1c40106d097bb1faff9b6a77854" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gift_items" ADD CONSTRAINT "FK_9d539268989d90975d494aaf465" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_a3c3c1fcf0af6c7fe3fa24c48fa" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_bf5e4bafa832ab25748a4a3fb2c" FOREIGN KEY ("contributor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contributions" ADD CONSTRAINT "FK_c0f5b1634d4c1f17beada1437a7" FOREIGN KEY ("gift_item_id") REFERENCES "gift_items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fulfillments" ADD CONSTRAINT "FK_f20ee44c54cf1880b632ea57056" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_19d038a0d2bef43b30dad96c725" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_669fdec7c1734fcfb4043042899" FOREIGN KEY ("accepted_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circles" ADD CONSTRAINT "FK_4ab77e121c9178f12fdb4999339" FOREIGN KEY ("organizer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_8769073e38c365f315426554ca5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation_reports" ADD CONSTRAINT "FK_2a75fb514f2d13b13616066fd20" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation_reports" ADD CONSTRAINT "FK_7e8a1a25e0550ef6ae2802c14fb" FOREIGN KEY ("reviewed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contribution_ledger_entries" ADD CONSTRAINT "FK_9c5b2974bf7233f7059834ae4f6" FOREIGN KEY ("contribution_id") REFERENCES "contributions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contribution_ledger_entries" ADD CONSTRAINT "FK_225d73df36d1d7ec14075334eaf" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_messages" ADD CONSTRAINT "FK_5a6ce140c7c487972d92516d456" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_messages" ADD CONSTRAINT "FK_bbe3ef4431b57dcde702da191a5" FOREIGN KEY ("contribution_id") REFERENCES "contributions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_broadcasts" ADD CONSTRAINT "FK_3c520ca7f10b06fbb93787b4b0f" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_514504661af7cfe190a40024b6a" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_memberships" ADD CONSTRAINT "FK_fa2a9a24866bde1d5b4f1cddefa" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_memberships" ADD CONSTRAINT "FK_fb442a92eb5b1e2dbeeec00bccb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "circle_memberships" ADD CONSTRAINT "FK_9f367ab2be82a42317f440e56bc" FOREIGN KEY ("invitation_id") REFERENCES "invitations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_address_records" ADD CONSTRAINT "FK_9107d6197c090a7c85054c3ec37" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "delivery_address_records" DROP CONSTRAINT "FK_9107d6197c090a7c85054c3ec37"`);
        await queryRunner.query(`ALTER TABLE "circle_memberships" DROP CONSTRAINT "FK_9f367ab2be82a42317f440e56bc"`);
        await queryRunner.query(`ALTER TABLE "circle_memberships" DROP CONSTRAINT "FK_fb442a92eb5b1e2dbeeec00bccb"`);
        await queryRunner.query(`ALTER TABLE "circle_memberships" DROP CONSTRAINT "FK_fa2a9a24866bde1d5b4f1cddefa"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_514504661af7cfe190a40024b6a"`);
        await queryRunner.query(`ALTER TABLE "circle_broadcasts" DROP CONSTRAINT "FK_3c520ca7f10b06fbb93787b4b0f"`);
        await queryRunner.query(`ALTER TABLE "circle_messages" DROP CONSTRAINT "FK_bbe3ef4431b57dcde702da191a5"`);
        await queryRunner.query(`ALTER TABLE "circle_messages" DROP CONSTRAINT "FK_5a6ce140c7c487972d92516d456"`);
        await queryRunner.query(`ALTER TABLE "contribution_ledger_entries" DROP CONSTRAINT "FK_225d73df36d1d7ec14075334eaf"`);
        await queryRunner.query(`ALTER TABLE "contribution_ledger_entries" DROP CONSTRAINT "FK_9c5b2974bf7233f7059834ae4f6"`);
        await queryRunner.query(`ALTER TABLE "moderation_reports" DROP CONSTRAINT "FK_7e8a1a25e0550ef6ae2802c14fb"`);
        await queryRunner.query(`ALTER TABLE "moderation_reports" DROP CONSTRAINT "FK_2a75fb514f2d13b13616066fd20"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_8769073e38c365f315426554ca5"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "circles" DROP CONSTRAINT "FK_4ab77e121c9178f12fdb4999339"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_669fdec7c1734fcfb4043042899"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_19d038a0d2bef43b30dad96c725"`);
        await queryRunner.query(`ALTER TABLE "fulfillments" DROP CONSTRAINT "FK_f20ee44c54cf1880b632ea57056"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_c0f5b1634d4c1f17beada1437a7"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_bf5e4bafa832ab25748a4a3fb2c"`);
        await queryRunner.query(`ALTER TABLE "contributions" DROP CONSTRAINT "FK_a3c3c1fcf0af6c7fe3fa24c48fa"`);
        await queryRunner.query(`ALTER TABLE "gift_items" DROP CONSTRAINT "FK_9d539268989d90975d494aaf465"`);
        await queryRunner.query(`ALTER TABLE "gift_items" DROP CONSTRAINT "FK_1c40106d097bb1faff9b6a77854"`);
        await queryRunner.query(`ALTER TABLE "circle_updates" DROP CONSTRAINT "FK_80efa3fc9b52b316940185090dc"`);
        await queryRunner.query(`ALTER TABLE "circle_updates" DROP CONSTRAINT "FK_feb81287d37d9124092520f6a10"`);
        await queryRunner.query(`ALTER TABLE "circle_activities" DROP CONSTRAINT "FK_e3eede368064d5f8a770329d68f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_catalog_items_search"`);
        await queryRunner.query(`DROP TABLE "catalog_items"`);
        await queryRunner.query(`DROP TABLE "delivery_address_records"`);
        await queryRunner.query(`DROP TABLE "circle_memberships"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TABLE "circle_broadcasts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_circle_messages_circle_created"`);
        await queryRunner.query(`DROP TABLE "circle_messages"`);
        await queryRunner.query(`DROP TABLE "contribution_ledger_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_moderation_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_moderation_target"`);
        await queryRunner.query(`DROP TABLE "moderation_reports"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_reports_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_reports_target_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tokens_user_type"`);
        await queryRunner.query(`DROP TABLE "tokens"`);
        await queryRunner.query(`DROP TYPE "public"."tokens_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_read"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_circles_organizer_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_circles_discovery"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_circles_publish_idempotency_key"`);
        await queryRunner.query(`DROP TABLE "circles"`);
        await queryRunner.query(`DROP TYPE "public"."circles_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."circles_privacy_enum"`);
        await queryRunner.query(`DROP TYPE "public"."circles_occasion_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invitations_circle_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invitations_token_hash"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_status_enum"`);
        await queryRunner.query(`DROP TABLE "fulfillments"`);
        await queryRunner.query(`DROP TYPE "public"."fulfillments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contributions_circle_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contributions_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_contributions_idempotency_key"`);
        await queryRunner.query(`DROP TABLE "contributions"`);
        await queryRunner.query(`DROP TYPE "public"."contributions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."contributions_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_gift_items_circle_status"`);
        await queryRunner.query(`DROP TABLE "gift_items"`);
        await queryRunner.query(`DROP TYPE "public"."gift_items_status_enum"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "circle_updates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_activities_circle_created"`);
        await queryRunner.query(`DROP TABLE "circle_activities"`);
        await queryRunner.query(`DROP TYPE "public"."circle_activities_type_enum"`);
    }

}
